#!/usr/bin/env python3
"""Generate or update the Homebrew cask for Endara Desktop.

Renders Casks/endara.rb from a fixed template using the provided version and
per-arch SHA256 sums. Idempotent: writing the same inputs twice produces the
same file. Works for both create-from-scratch and in-place update.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

CASK_TEMPLATE = """\
# This file is auto-generated by endara-ai/endara-desktop's release workflow.
# Manual edits will be overwritten on the next release.
cask "endara" do
  arch arm: "aarch64", intel: "x64"

  version "{version}"
  sha256 arm:   "{sha_arm64}",
         intel: "{sha_x64}"

  url "https://github.com/endara-ai/endara-desktop/releases/download/v#{{version}}/Endara.Desktop_#{{version}}_#{{arch}}.dmg"
  name "Endara"
  desc "Desktop app for managing the Endara MCP server aggregator"
  homepage "https://github.com/endara-ai/endara-desktop"

  auto_updates true
  depends_on macos: ">= :catalina"

  app "Endara Desktop.app"

  zap trash: [
    "~/Library/Application Support/ai.endara.desktop",
    "~/Library/Caches/ai.endara.desktop",
    "~/Library/HTTPStorages/ai.endara.desktop",
    "~/Library/Logs/Endara Desktop",
    "~/Library/Preferences/ai.endara.desktop.plist",
    "~/Library/Saved Application State/ai.endara.desktop.savedState",
    "~/Library/WebKit/ai.endara.desktop",
  ]
end
"""


def render(version: str, sha_arm64: str, sha_x64: str) -> str:
    return CASK_TEMPLATE.format(
        version=version,
        sha_arm64=sha_arm64,
        sha_x64=sha_x64,
    )


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", required=True, help="Version without leading 'v', e.g. 0.1.1")
    parser.add_argument("--sha256-arm64", required=True, dest="sha_arm64")
    parser.add_argument("--sha256-x64", required=True, dest="sha_x64")
    parser.add_argument(
        "--cask-path",
        required=True,
        type=Path,
        help="Path to Casks/endara.rb (created if missing).",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    if args.version.startswith("v"):
        print(f"--version must not start with 'v' (got {args.version!r})", file=sys.stderr)
        return 2
    rendered = render(
        version=args.version,
        sha_arm64=args.sha_arm64,
        sha_x64=args.sha_x64,
    )
    cask_path: Path = args.cask_path
    cask_path.parent.mkdir(parents=True, exist_ok=True)
    existed = cask_path.exists()
    cask_path.write_text(rendered, encoding="utf-8")
    action = "Updated" if existed else "Created"
    print(f"{action} {cask_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

